### ISSUE TITLE
Use http/ws schema by location.protocol

### ISSUE THREAD

**Issue by wancom** [wonder-wonder/cakemix-front#239]
**Is your feature request related to a problem? Please describe.**
Currently, http/ws schema is decided when building.
However, it is not useful for distribution. (We need to prepare both http and https version.)

**Describe the solution you'd like**
If the schema is not defined and building mode is production, we can use `location.protocol` to decide http or https.
```
... location.protocol === "http:" ? "http" : "https"
... location.protocol === "http:" ? "ws" : "wss"
```
https://github.com/wonder-wonder/cakemix-front/blob/2da839da5f815f1ec9ed4317c49a0708e707f6d5/scripts/api/base.ts#L20-L21

**Describe alternatives you've considered**
In current implementation, it is better the above.
Or we may omit the schema and domain if the front and API server is same origin.

**Additional context**
refer https://developer.mozilla.org/ja/docs/Web/API/Location

**Comment by 0eta0** [comment]
@wancom
Thank you, it looks good, I will reflect it in the next version!
